import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className={styles.titleContainer}>
      <h1 className={styles.title}>You Are The Password.</h1>
    </div>

    <div className={styles.descriptionContainer}>
      <h2 className={styles.description}>Tired of remembering countless passwords? Worried about your online account security?<br/>BioPass has you covered by turning your unique biometric signature into the only password you'll ever need.</h2>
      </div>
      
      <div className={styles.buttonsContainer}>
        <div className={styles.signUp}>
          <Link href="/sign-up/step1" >
            <a>
              <button className={styles.linkButton}>Sign Up</button>
            </a>
          </Link>
          
          <div className={styles.belowText}>
              Don't have an account? <br/> Make one!
          </div>
        </div>
      
        <div className={styles.login}>
          <Link href="/login/step1" >
            <a>
              <button className={styles.linkButton}>Login</button>
            </a>
          </Link>
          <div className={styles.belowText}>
              Have an account?<br/> Login!
          </div>
        </div>

        
      </div>

    </div>
  )
}

{/* <footer className={styles.footer}>
<a
  href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  target="_blank"
  rel="noopener noreferrer"
>
  Powered by{' '}
  <span className={styles.logo}>
    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  </span>
</a>
</footer> */}