import { FC } from 'react';
import styles from "../../styles/passwords/PasswordsHome.module.css"
import Head from "next/head"
import Link from 'next/link'
import PasswordsSection from '../../comps/Layout/Passwords/PasswordsSection';

const PasswordsHome: FC = () => {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.headerContainer}>
        <div className={styles.titleContainer}>
          <h1 className={styles.title}>
            Pass<span>words</span>
          </h1>
        </div>
      
        <div className={styles.addPassContainer}>
          <Link href="/passwords/add-password">
            <a>
              <button className={styles.addPasswordButton}>
                Add Password
              </button>
            </a>
          </Link>
          
        </div>
      </div>

      <div className={styles.sectionWrapper}>
        <div className={styles.mainContainer}>
          <PasswordsSection />
        </div>
      </div>
      




    </div>
  )
}

export default PasswordsHome